---
- name: install prerequisites
  yum:
    name: yum-utils
    state: latest
    update_cache: true

- name: Create Nginx repo
  copy:
    dest: "/etc/yum.repos.d/nginx.repo"
    content: |
      [nginx-stable]
      name=nginx stable repo
      baseurl=http://nginx.org/packages/centos/$releasever/$basearch/
      gpgcheck=1
      enabled=1
      gpgkey=https://nginx.org/keys/nginx_signing.key
      module_hotfixes=true

      [nginx-mainline]
      name=nginx mainline repo
      baseurl=http://nginx.org/packages/mainline/centos/$releasever/$basearch/
      gpgcheck=1
      enabled=0
      gpgkey=https://nginx.org/keys/nginx_signing.key
      module_hotfixes=true

- name: switch to mainline nginx packages
  shell: yum-config-manager --enable nginx-mainline

- name: install nginx
  yum:
    name: nginx
    state: latest
    update_cache: true